export interface DayContent {
  day: number
  title: string
  subtitle: string
  audioFile: string // filename in Supabase Storage bucket 'programa-audio'
  durationMinutes: number
  description: string
  technique: string
}

export const WEEK_NAMES = [
  'Semana 1 · Activación',
  'Semana 2 · Integración',
  'Semana 3 · Consolidación',
]

export const PROGRAM_CONTENT: DayContent[] = [
  {
    day: 1,
    title: 'La Espiración Larga',
    subtitle: 'Activación del nervio vago en 30 segundos',
    audioFile: 'dia-01.mp3',
    durationMinutes: 12,
    description: 'La base de todo el protocolo. Aprenderás por qué la espiración es más poderosa que la inspiración para regular el sistema nervioso.',
    technique: 'Espiración 4:8',
  },
  {
    day: 2,
    title: 'El Sonido Interno',
    subtitle: 'Vibración vagal a través de la voz',
    audioFile: 'dia-02.mp3',
    durationMinutes: 14,
    description: 'Tu voz es una herramienta directa de modulación vagal. La vibración de ciertas consonantes activa el nervio vago desde la garganta.',
    technique: 'Humming / Vocalización',
  },
  {
    day: 3,
    title: 'La Mirada Periférica',
    subtitle: 'El reset visual del sistema nervioso',
    audioFile: 'dia-03.mp3',
    durationMinutes: 11,
    description: 'Los ojos están directamente conectados al estado del sistema nervioso. Esta técnica activa el modo parasimpático en segundos.',
    technique: 'Visión panorámica',
  },
  {
    day: 4,
    title: 'El Peso del Cuerpo',
    subtitle: 'Activación propioceptiva profunda',
    audioFile: 'dia-04.mp3',
    durationMinutes: 13,
    description: 'La presión física envía señales de seguridad directas al sistema nervioso. Aprenderás a usarla como ancla de regulación.',
    technique: 'Propioceptiva + presión',
  },
  {
    day: 5,
    title: 'El Frío como Herramienta',
    subtitle: 'Estimulación vagal con temperatura',
    audioFile: 'dia-05.mp3',
    durationMinutes: 10,
    description: 'La exposición breve al frío es uno de los activadores vagales más potentes documentados. Sin inmersión, sin incomodidad extrema.',
    technique: 'Exposición térmica controlada',
  },
  {
    day: 6,
    title: 'La Pausa Activa',
    subtitle: 'Regulación en medio del ruido',
    audioFile: 'dia-06.mp3',
    durationMinutes: 15,
    description: 'Cómo usar microinterrupciones para resetear el sistema nervioso sin salir del contexto de tu día.',
    technique: 'Microrregulación',
  },
  {
    day: 7,
    title: 'Integración Semana 1',
    subtitle: 'Consolidar lo que el cuerpo aprendió',
    audioFile: 'dia-07.mp3',
    durationMinutes: 18,
    description: 'Revisión guiada de las 6 técnicas. Tu sistema nervioso ya ha empezado a cambiar — hoy lo hacemos consciente.',
    technique: 'Revisión integrada',
  },
  {
    day: 8,
    title: 'La Respiración Alterna',
    subtitle: 'Balance hemisférico a través de la nariz',
    audioFile: 'dia-08.mp3',
    durationMinutes: 13,
    description: 'Cada fosa nasal conecta con un hemisferio cerebral diferente. Esta técnica clásica del pranayama tiene base neurocientífica sólida.',
    technique: 'Nadi Shodhana adaptado',
  },
  {
    day: 9,
    title: 'El Movimiento de Ojos',
    subtitle: 'Procesamiento de estrés acumulado',
    audioFile: 'dia-09.mp3',
    durationMinutes: 14,
    description: 'Movimientos oculares específicos activan el procesamiento de memorias de estrés. Base del protocolo EMDR simplificado.',
    technique: 'Desensibilización ocular',
  },
  {
    day: 10,
    title: 'La Mandíbula',
    subtitle: 'Liberar la tensión crónica facial',
    audioFile: 'dia-10.mp3',
    durationMinutes: 12,
    description: 'La mandíbula acumula tensión del sistema nervioso simpático. Relajarla tiene efecto cascada sobre todo el cuerpo.',
    technique: 'Liberación mandibular',
  },
  {
    day: 11,
    title: 'El Zumbido Interno',
    subtitle: 'Vibración en el pecho y garganta',
    audioFile: 'dia-11.mp3',
    durationMinutes: 11,
    description: 'Técnica avanzada de humming con resonancia torácica. Activa ramas vagales que la espiración sola no alcanza.',
    technique: 'Resonancia vagal profunda',
  },
  {
    day: 12,
    title: 'El Ancla Sensorial',
    subtitle: 'Crear un gatillo de regulación propio',
    audioFile: 'dia-12.mp3',
    durationMinutes: 16,
    description: 'Construirás un ancla sensorial personalizada que podrás activar en cualquier momento de estrés con un gesto.',
    technique: 'Anclaje condicionado',
  },
  {
    day: 13,
    title: 'Sueño y Sistema Nervioso',
    subtitle: 'El protocolo nocturno',
    audioFile: 'dia-13.mp3',
    durationMinutes: 17,
    description: 'Lo que haces antes de dormir determina la calidad de tu recuperación vagal. Una secuencia de 8 minutos que cambia el sueño.',
    technique: 'Protocolo nocturno',
  },
  {
    day: 14,
    title: 'Integración Semana 2',
    subtitle: 'El sistema nervioso como aliado',
    audioFile: 'dia-14.mp3',
    durationMinutes: 20,
    description: 'En 14 días tu sistema nervioso ha registrado nuevos patrones. Hoy los consolidamos y exploramos cómo seguir solos.',
    technique: 'Mapa personal de regulación',
  },
  {
    day: 15,
    title: 'El Tono Vagal en Movimiento',
    subtitle: 'Regulación mientras caminas',
    audioFile: 'dia-15.mp3',
    durationMinutes: 13,
    description: 'El movimiento rítmico sincronizado con la respiración multiplica los efectos vagales. No necesitas ir al gimnasio.',
    technique: 'Caminata vagal',
  },
  {
    day: 16,
    title: 'La Voz Grave',
    subtitle: 'Modulación vagal con resonancia baja',
    audioFile: 'dia-16.mp3',
    durationMinutes: 12,
    description: 'Las frecuencias vocales graves tienen mayor efecto vagal que las agudas. Aprenderás a usarlas con intención.',
    technique: 'Vocalización de baja frecuencia',
  },
  {
    day: 17,
    title: 'El Bostejo Inducido',
    subtitle: 'El reset más natural del sistema nervioso',
    audioFile: 'dia-17.mp3',
    durationMinutes: 10,
    description: 'El bostezo es una de las respuestas reguladoras más potentes del sistema nervioso. Se puede inducir. Se puede entrenar.',
    technique: 'Inducción de bostezo',
  },
  {
    day: 18,
    title: 'Conexión Social como Regulación',
    subtitle: 'El nervio vago en la interacción',
    audioFile: 'dia-18.mp3',
    durationMinutes: 15,
    description: 'La teoría polivagal explica por qué ciertas interacciones regulan y otras desregulan. Aprenderás a elegir las primeras.',
    technique: 'Co-regulación consciente',
  },
  {
    day: 19,
    title: 'La Gratitud Fisiológica',
    subtitle: 'Más allá del optimismo — cambio real en el sistema nervioso',
    audioFile: 'dia-19.mp3',
    durationMinutes: 14,
    description: 'La gratitud genuina — no positiva tóxica — produce cambios medibles en la variabilidad de la frecuencia cardíaca.',
    technique: 'Activación vagal por gratitud',
  },
  {
    day: 20,
    title: 'Tu Protocolo Personalizado',
    subtitle: 'Diseñar tu práctica de por vida',
    audioFile: 'dia-20.mp3',
    durationMinutes: 16,
    description: 'Con todas las técnicas integradas, construirás tu protocolo personalizado de 5-10 minutos diarios para mantener el tono vagal.',
    technique: 'Diseño de protocolo propio',
  },
  {
    day: 21,
    title: 'El Sistema Nervioso Regulado',
    subtitle: 'Lo que has logrado y lo que sigue',
    audioFile: 'dia-21.mp3',
    durationMinutes: 22,
    description: 'La sesión final. Un repaso completo de tu transformación, las métricas de tu tono vagal, y el camino que tienes por delante.',
    technique: 'Integración final',
  },
]

export const COMPLETION_MESSAGES: Record<number, string> = {
  0: 'Bienvenido al programa. Tu sistema nervioso está listo.',
  1: 'Día 1 completado. La espiración larga es tuya ya.',
  2: 'Tu voz ya trabaja para ti. Sigue.',
  3: 'La mirada periférica cambia cómo ves el mundo — literalmente.',
  4: 'Cuatro días. Tu cuerpo ya sabe que puede regularse.',
  5: 'El frío ya no es el enemigo. Es tu herramienta.',
  6: 'Seis técnicas. Seis formas de volver a ti mismo.',
  7: 'Primera semana completa. El cambio ya empezó.',
  8: 'Tu respiración ahora trabaja en dos vías.',
  9: 'Nueve días de práctica. El sistema nervioso tiene memoria.',
  10: 'La tensión que guardabas en la mandíbula ya tiene salida.',
  11: 'Once días. El zumbido interno es tuyo.',
  12: 'Tu ancla sensorial ya existe. Úsala.',
  13: 'El sueño ya forma parte del protocolo.',
  14: 'Dos semanas. Tu sistema nervioso ya no es el mismo.',
  15: 'Caminar nunca volverá a ser solo caminar.',
  16: 'La voz grave es una herramienta que llevas siempre contigo.',
  17: 'El bostezo es ahora un acto consciente. Poderoso.',
  18: 'Sabes ya qué conexiones regulan y cuáles desregulan.',
  19: 'La gratitud tiene ahora base fisiológica para ti.',
  20: 'Tu protocolo propio existe. Es tuyo.',
  21: '21 días. Has regulado tu sistema nervioso. Continúa.',
}
